[package]
name = "image-rotator"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/image-rotator.rs"
crate-type = ["cdylib"]

[dependencies]
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
regex = "1.6.0"
